version: "3.1"
services:
  db:
    #container_name: some-postgres
    image: postgres:12
    # restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    # volumes:
    #   - ./db-data:/var/lib/postgresql/data
    # dont forget to add your ./db-data to .gitignore
    ports:
      - 5432:5432
