version: "3.1"
services:
  db:
    #container_name: some-postgres
    image: postgres:12
    # restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumnes:
       - db-data:/var/lib/postgresql/data
