# This is a basic workflow to help you get started with Actions

name: Commit Things
on:
  push:
    paths:
      - ".github/workflows/commit.yml"
  pull_request:
    paths:
      - ".github/workflows/commit.yml"
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Make a webrequest and commit it
    steps:
      # To use add these to the repo again
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: File output
        run: curl -v --silent http://citylab-berlin.org 2>&1  | grep -Eho "Date(.*?)$" > day-two-testing/workflow-commit-data/time.txt
        # https://github.com/marketplace/actions/add-commit?version=v4.4.0
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0 # You can change this to use a specific version
        with:
          add: day-two-testing/workflow-commit-data/
          author_name: tsboter
          author_email: roboter@tsb-berlin.de
          message: "Update ${{ steps.pumps.outputs.file }} via workflow"
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        # Runs a set of commands using the runners shell
